import {
  Zap,
  Sun,
  Battery,
  Home,
  Briefcase,
  Shield,
  Leaf,
} from "lucide-react";

export const nigerianStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const systemCapacities = [
  {
    value: "200w/kwh power station",
    label: "200W Power Station",
    price: "₦150,000 - ₦300,000",
    description: "Perfect for small devices and emergency backup",
    icon: Battery,
    features: ["Portable", "USB charging", "LED lighting", "Phone charging"],
  },
  {
    value: "1.5kva inverter",
    label: "1.5KVA Inverter System",
    price: "₦400,000 - ₦800,000",
    description: "Ideal for small homes and apartments",
    icon: Home,
    features: ["Basic appliances", "Lighting", "TV & Fan", "Small fridge"],
  },
  {
    value: "3.5kva inverter",
    label: "3.5KVA Inverter System",
    price: "₦800,000 - ₦1,500,000",
    description: "Great for medium-sized homes",
    icon: Zap,
    features: ["Multiple rooms", "AC (small)", "Washing machine", "All lighting"],
  },
  {
    value: "5kva inverter",
    label: "5KVA Inverter System",
    price: "₦1,200,000 - ₦2,500,000",
    description: "Perfect for large homes",
    icon: Sun,
    features: ["Full home power", "Multiple ACs", "All appliances", "24/7 backup"],
  },
  {
    value: "10kva inverter",
    label: "10KVA Inverter System",
    price: "₦2,500,000 - ₦4,500,000",
    description: "Commercial grade for businesses",
    icon: Briefcase,
    features: ["Office buildings", "Small business", "Heavy appliances", "Industrial use"],
  },
  {
    value: "20kva inverter",
    label: "20KVA Inverter System",
    price: "₦4,500,000 - ₦8,000,000",
    description: "Large commercial applications",
    icon: Shield,
    features: ["Large offices", "Factories", "Multiple units", "High capacity"],
  },
  {
    value: "50kva inverter",
    label: "50KVA Inverter System",
    price: "₦8,000,000 - ₦15,000,000",
    description: "Industrial scale solutions",
    icon: Leaf,
    features: ["Industrial plants", "Large facilities", "Grid-tie capable", "Maximum power"],
  },
];

export const occupations = ["Unemployed", "Employed", "Self-employed"];

export const workplaceSectors = ["Private", "Public (Government)", "Non-profit", "Other - please specify"];

export const paymentPlans = [
  { value: "Outright", label: "Outright Payment", },
  { value: "3 months", label: "3 Months",},
  { value: "6 months", label: "6 Months",},
  { value: "8 months", label: "8 Months",},
  { value: "12 months", label: "12 Months", },
  { value: "18 months", label: "18 Months",},
  { value: "21 months", label: "21 Months",},
];