import {
  Zap,
  Sun,
  Battery,
  Home,
  Briefcase,
  Shield,
  Leaf,
} from "lucide-react";

export const nigerianStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const systemCapacities = [
  {
    value: "200w/kwh power station",
    label: "200W Power Station",
    price: "₦350,000",
    description: "Perfect for small devices and emergency backup",
    included: "1KWh Lithium Battery | 200w solar panel",
    icon: Battery,
    features: ["Portable", "USB charging", "LED lighting", "Phone charging"],
  },
    {
    value: "1000w/kwh power station",
    label: "1000W Power Station",
    price: "₦864,000",
    description: "Perfect for small devices and emergency backup",
    included: "2KWh Lithium Battery | 450w solar panel 1pcs",
    icon: Battery,
    features: ["Portable", "USB charging", "LED lighting", "Phone charging"],
  },
  {
    value: "1kva inverter",
    label: "1KVA Inverter System",
    price: "₦1,020,000",
    description: "Ideal for small homes and apartments",
    included: "12V 200Ah Tubbular Battery 1pcs| Charge Controller 40A | Solar Panel 550W 2pcs",
    icon: Home,
    features: ["Basic appliances", "Lighting", "TV & Fan", "Small fridge"],
  },
  {
    value: "1.5kva inverter",
    label: "1.5KVA Inverter System",
    price: "₦1,974,000",
    description: "Ideal for small homes and apartments",
    included: "12V 200Ah Tubbular Battery 2pcs| Charge Controller 60A | Solar Panel 550W 4pcs",
    icon: Home,
    features: ["Basic appliances", "Lighting", "TV & Fan", "Small fridge"],
  },
  {
    value: "2.5kva inverter",
    label: "2.5KVA/24V Inverter System",
    price: "₦2,130,000",
    description: "Great for medium-sized homes",
    included: "12V 200Ah Tubbular Battery 2pcs| Charge Controller 60A | Solar Panel 550W 4pcs",
    icon: Zap,
    features: ["Multiple rooms", "AC (small)", "Washing machine", "All lighting"],
  },
  {
    value: "3.5kva/24V inverter",
    label: "3.5KVA Inverter System",
    price: "₦4,092,000",
    description: "Great for medium-sized homes",
    included: "12V 200Ah Tubbular Battery 4pcs| Charge Controller 100A | Solar Panel 550W 8pcs",
    icon: Zap,
    features: ["Multiple rooms", "AC (small)", "Washing machine", "All lighting"],
  },
  {
    value: "4kva inverter",
    label: "4KVA/48V Inverter System",
    price: "₦4,308,000",
    description: "Great for medium-sized homes",
    included: "12V 200Ah Tubbular Battery 4pcs| Charge Controller 100A | Solar Panel 550W 8pcs",
    icon: Zap,
    features: ["Multiple rooms", "AC (small)", "Washing machine", "All lighting"],
  },
  {
    value: "5kva inverter",
    label: "5KVA/48V Inverter System",
    price: "₦4,534,978.08",
    description: "Perfect for large homes",
    included: "5KWH Lithium Ion Battery | Solar Panel 550W 6pcs",
    icon: Sun,
    features: ["Full home power", "Multiple ACs", "All appliances", "24/7 backup"],
  },
  {
    value: "10kva inverter",
    label: "10KVA Inverter System",
    price: "₦7,855,594.56",
    description: "Commercial grade for businesses",
    included: "10KWH Lithium Ion Battery | Solar Panel 550W 12pcs",
    icon: Briefcase,
    features: ["Office buildings", "Small business", "Heavy appliances", "Industrial use"],
  },
   {
    value: "12kva inverter",
    label: "12KVA Inverter System",
    price: "₦12,752,700",
    description: "Commercial grade for businesses",
    included: "15KWH Lithium Ion Battery | Solar Panel 550W 20pcs",
    icon: Briefcase,
    features: ["Office buildings", "Small business", "Heavy appliances", "Industrial use"],
  },
  {
    value: "15kva inverter",
    label: "15KVA Inverter System",
    price: "₦14,295,908.16",
    description: "Commercial grade for businesses",
    included: "20KWH Lithium Ion Battery | Solar Panel 550W 20pcs",
    icon: Briefcase,
    features: ["Office buildings", "Small business", "Heavy appliances", "Industrial use"],
  },
  {
    value: "20kva inverter",
    label: "20KVA Inverter System",
    price: "₦24,065,486",
    description: "Large commercial applications",
    included: "40KWH Lithium Ion Battery | Solar Panel 550W 40pcs",
    icon: Shield,
    features: ["Large offices", "Factories", "Multiple units", "High capacity"],
  },
  {
    value: "30kva inverter",
    label: "30KVA Inverter System",
    price: "₦27,635,095",
    description: "Large commercial applications",
    included: "40KWH Lithium Ion Battery | Solar Panel 550W 40pcs",
    icon: Shield,
    features: ["Large offices", "Factories", "Multiple units", "High capacity"],
  },
  {
    value: "50kva inverter",
    label: "50KVA Inverter System",
    price: "₦39,957,676",
    description: "Industrial scale solutions",
    included: "60KWH Lithium Ion Battery | Solar Panel 550W 60pcs",
    icon: Leaf,
    features: ["Industrial plants", "Large facilities", "Grid-tie capable", "Maximum power"],
  },
];

export const occupations = ["Unemployed", "Employed", "Self-employed"];

export const workplaceSectors = ["Private", "Public (Government)", "Non-profit", "Other - please specify"];

export const paymentPlans = [
  { value: "Outright", label: "Outright Payment", },
  { value: "3 months", label: "3 Months",},
  { value: "6 months", label: "6 Months",},
  { value: "8 months", label: "8 Months",},
  { value: "12 months", label: "12 Months", },
  { value: "18 months", label: "18 Months",},
  { value: "21 months", label: "21 Months",},
];

export const salaryRanges = [
  { value: "  ₦50,000 - ₦100,000", label: "step1"},
  { value: "  ₦100,000 - ₦300,000", label: "step2"},
  { value: "  ₦300,000 - ₦500,000", label: "step3"},
  { value: "  ₦500,000 - ₦700,000", label: "step4"},
  { value: "  ₦700,000 - Above", label: "step5"},
];